### ISSUE TITLE
Can ypu provide sinhala lexicon file for given dataset here?

### ISSUE THREAD

**Issue by pasindumadusanka95** [pnfo/sinhala-tts-dataset#2]

**Comment by pasindumadusanka95** [comment]
අංකල්ට	a ŋ k ə l ʈ ə
අංකල්ටත්	a ŋ k ə l ʈ a t
අංකවලට	a ŋ k ə w ə l ə ʈ ə
අංකවලින්	a ŋ k ə w ə l i n
අංකුර	a ŋ k u r ə
අංකුරය	a ŋ k u r ə y ə
අංකුරයක්	a ŋ k u r ə y a k
අංකෙ	a ŋ k e
අංකෙන්	a ŋ k e n
අංකෙලිය	a ŋ k e l i y ə
අංකෙළිය	a ŋ k e l i y ə

Like this. to map characters

**Comment by pathnirvana** [comment]
yes this is already available in metadata.csv file
https://github.com/pnfo/sinhala-tts-dataset/blob/main/metadata.csv
